import { useMemo, useState } from 'react'
import './App.css'
import {
  decisionOptions,
  evaluateDecision,
  questions,
  type AnswerSet,
  type DecisionOption,
  type Question,
  type RecommendationResult,
} from './decisionEngine'

const initialAnswers: AnswerSet = Object.fromEntries(
  questions.map((question) => [question.id, question.choices[0].id]),
)

const formatOptionName = (option: DecisionOption) => option.name

const buildMarkdownExport = (result: RecommendationResult) => {
  const lines = [
    '# Migration Decision Assistant result',
    '',
    `Recommended path: ${result.winner.name}`,
    `Score: ${result.winnerScore.total}`,
    `Confidence: ${result.confidence}`,
    '',
    '## Why this scored highest',
    ...result.rationales.map((rationale) => `- ${rationale}`),
    '',
    '## Important cautions',
    ...result.cautions.map((caution) => `- ${caution}`),
    '',
    '## Scores',
    '| Option | Score | Best fit | Watch-outs |',
    '| --- | ---: | --- | --- |',
    ...result.scores.map(
      (score) =>
        `| ${score.option.name} | ${score.total} | ${score.option.bestFit} | ${score.option.watchOut} |`,
    ),
    '',
    '## Answers',
    ...result.answeredQuestions.map(
      (answer) => `- ${answer.question}: ${answer.choice}`,
    ),
    '',
    'Generated by a deterministic, rule-based assistant. This is not a substitute for a formal architecture assessment.',
  ]

  return lines.join('\n')
}

const downloadFile = (filename: string, content: string, type: string) => {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

const QuestionCard = ({
  question,
  answer,
  onAnswer,
}: {
  question: Question
  answer: string
  onAnswer: (questionId: string, choiceId: string) => void
}) => (
  <fieldset className="question-card">
    <legend>
      <span>{question.category}</span>
      {question.prompt}
    </legend>
    <div className="choice-grid">
      {question.choices.map((choice) => (
        <label
          className={choice.id === answer ? 'choice selected' : 'choice'}
          key={choice.id}
        >
          <input
            checked={choice.id === answer}
            name={question.id}
            onChange={() => onAnswer(question.id, choice.id)}
            type="radio"
            value={choice.id}
          />
          <strong>{choice.label}</strong>
          <small>{choice.description}</small>
        </label>
      ))}
    </div>
  </fieldset>
)

const ScoreBar = ({
  score,
  maxScore,
}: {
  score: number
  maxScore: number
}) => {
  const width = maxScore === 0 ? 0 : Math.max(8, Math.round((score / maxScore) * 100))

  return (
    <div className="score-bar" aria-label={`${score} points`}>
      <span style={{ width: `${width}%` }} />
    </div>
  )
}

function App() {
  const [answers, setAnswers] = useState<AnswerSet>(initialAnswers)
  const result = useMemo(() => evaluateDecision(answers), [answers])
  const maxScore = Math.max(...result.scores.map((score) => score.total), 1)

  const updateAnswer = (questionId: string, choiceId: string) => {
    setAnswers((current) => ({ ...current, [questionId]: choiceId }))
  }

  const resetAnswers = () => setAnswers(initialAnswers)

  const exportJson = () => {
    downloadFile(
      'migration-decision-result.json',
      JSON.stringify(result, null, 2),
      'application/json',
    )
  }

  const exportMarkdown = () => {
    downloadFile(
      'migration-decision-result.md',
      buildMarkdownExport(result),
      'text/markdown',
    )
  }

  return (
    <main>
      <section className="hero">
        <p className="eyebrow">Public V1 architecture scoping assistant</p>
        <div className="hero-layout">
          <div>
            <h1>Migration Decision Assistant</h1>
            <p className="hero-copy">
              Choose between Azure Local, Azure Red Hat OpenShift, and Windows
              Server / Hyper-V with explicit scoring rules instead of freeform
              AI reasoning.
            </p>
          </div>
          <aside className="recommendation-card" aria-live="polite">
            <span>Current recommendation</span>
            <strong>{result.winner.name}</strong>
            <p>{result.winner.summary}</p>
            <div className="confidence">
              <b>{result.confidence}</b>
              <small>confidence based on score separation</small>
            </div>
          </aside>
        </div>
      </section>

      <section className="panel">
        <div className="section-heading">
          <div>
            <p className="eyebrow">Step 1</p>
            <h2>Answer the scoping questions</h2>
          </div>
          <button className="secondary" onClick={resetAnswers} type="button">
            Reset to defaults
          </button>
        </div>

        <div className="questions">
          {questions.map((question) => (
            <QuestionCard
              answer={answers[question.id]}
              key={question.id}
              onAnswer={updateAnswer}
              question={question}
            />
          ))}
        </div>
      </section>

      <section className="panel result-panel">
        <div className="section-heading">
          <div>
            <p className="eyebrow">Step 2</p>
            <h2>Review the deterministic result</h2>
          </div>
          <div className="actions">
            <button onClick={exportMarkdown} type="button">
              Export markdown
            </button>
            <button onClick={exportJson} type="button">
              Export JSON
            </button>
          </div>
        </div>

        <div className="winner">
          <div>
            <span>Recommended option</span>
            <h3>{formatOptionName(result.winner)}</h3>
            <p>{result.winner.bestFit}</p>
          </div>
          <strong>{result.winnerScore.total} pts</strong>
        </div>

        <div className="insight-grid">
          <article>
            <h3>Why this recommendation won</h3>
            <ul>
              {result.rationales.map((rationale) => (
                <li key={rationale}>{rationale}</li>
              ))}
            </ul>
          </article>
          <article>
            <h3>Cautions to validate</h3>
            <ul>
              {result.cautions.map((caution) => (
                <li key={caution}>{caution}</li>
              ))}
            </ul>
          </article>
        </div>
      </section>

      <section className="panel">
        <div className="section-heading">
          <div>
            <p className="eyebrow">Step 3</p>
            <h2>Compare the alternatives</h2>
          </div>
        </div>

        <div className="comparison-grid">
          {result.scores.map((score) => (
            <article
              className={
                score.option.id === result.winner.id
                  ? 'option-card recommended'
                  : 'option-card'
              }
              key={score.option.id}
            >
              <div className="option-card-header">
                <div>
                  <span>{score.option.category}</span>
                  <h3>{score.option.name}</h3>
                </div>
                <strong>{score.total}</strong>
              </div>
              <ScoreBar maxScore={maxScore} score={score.total} />
              <p>{score.option.summary}</p>
              <dl>
                {score.criteria.map((criterion) => (
                  <div key={criterion.name}>
                    <dt>{criterion.name}</dt>
                    <dd>{criterion.score}</dd>
                  </div>
                ))}
              </dl>
              <div className="fit-notes">
                <b>Best fit</b>
                <span>{score.option.bestFit}</span>
                <b>Watch-out</b>
                <span>{score.option.watchOut}</span>
              </div>
            </article>
          ))}
        </div>
      </section>

      <section className="panel rules-panel">
        <div>
          <p className="eyebrow">Transparent rules</p>
          <h2>How scoring works</h2>
          <p>
            Each answer applies fixed point impacts to the three options across
            workload fit, operating model, cloud integration, modernization,
            cost continuity, and risk readiness. The highest total wins. Ties
            are resolved by a fixed product order to keep outputs reproducible.
          </p>
        </div>
        <details>
          <summary>Show rule inventory</summary>
          <div className="rules-list">
            {questions.map((question) => (
              <article key={question.id}>
                <h3>{question.prompt}</h3>
                {question.choices.map((choice) => (
                  <p key={choice.id}>
                    <b>{choice.label}</b>: Azure Local {choice.impact.azureLocal},
                    ARO {choice.impact.aro}, Windows Server / Hyper-V{' '}
                    {choice.impact.windowsHyperV}
                  </p>
                ))}
              </article>
            ))}
          </div>
        </details>
      </section>

      <footer>
        <p>
          This V1 assistant is deterministic and explainable, but it is only an
          initial scoping aid. Validate final platform decisions with current
          product documentation, licensing, supportability, identity, security,
          networking, and operational requirements.
        </p>
        <p>
          Options tracked: {decisionOptions.map((option) => option.name).join(', ')}.
        </p>
      </footer>
    </main>
  )
}

export default App
